name: artifacts
on:
  workflow_dispatch:
jobs:
  artifacts:
    runs-on: windows-latest
    steps:
    - uses: actions/download-artifact@master
      with:
        name: nugets
        path: nugets/
    - run: ls nugets
