name: artifacts
on:
  workflow_dispatch:
jobs:
  artifacts:
    runs-on: windows-latest
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: main.yml
        workflow_conclusion: success
        branch: master
        name: nugets
        path: nugets
    - run: dotnet nuget push "nugets\*.nupkg" -s ".\."
    - run: ls \nugets_out
