name: Manual

on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          dotnet test 
          dotnet test -l:"trx;LogFileName=TEST-Lib.xml" 
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Test           # Name of the check run which will be created
          path: '**/TestResults/*.xml'    # Path to test results
          reporter: dotnet-trx 
      - name : Build nugets
        run : |
          dotnet pack -o nugets
      - name: Upload NuGets artifacts
        uses: actions/upload-artifact@v2  # upload test results
        if: success()         # run this step even if previous step failed
        with:
          name: nugets
          path: ${{ github.workspace }}/nugets/*.nupkg
