name: Build

on: 
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name : Run script
        run : |
          Write-Output ("BuildNumber=1.10.14-alpha-32") >> $env:GITHUB_ENV
      - name : Tag commits       
        if : env.BuildNumber && success() && github.event_name != 'pull_request'
        run : |
          git config --global user.email "gh-action@jozefchmelar.com"
          git config --global user.name "gh-action"
          $tag = "GH-${{github.run_id}}-${{env.BuildNumber}}"
          git tag $tag 
          git push --tags
