name: Build

on: 
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name : Tag commits
        run : |
          Write-Host ${{github.run_id	}}
          Write-Host ${{github.job}}          
