name: 'Test report'
on:
  workflow_run:
    workflows: ['Build','BuildCopy']
    types:
      - completed
jobs:
  report:
    runs-on: windows-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results            
        name: Test report
        path: '**/*.xml'
        reporter: dotnet-trx 
