name: 'After build'
on:
  workflow_run:
    workflows: ['Build']
    types:
      - completed
jobs:
  report:
    runs-on: windows-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results            
        name: Test report
        path: '**/*.xml'
        reporter: dotnet-trx 
        
  artifacts:
    needs : report
    runs-on: windows-latest
    steps:
    - uses: actions/download-artifact@master
      with:
        name: artifacts
        path: nugets/
    - run: ls nugets
